### PR TITLE
format errors in getBaseURL

### PR DESCRIPTION
**Pull request by dvrkps**
fmt.Errorf is cleaner way for formating error messages.

### CODE REVIEW

**Comment by olix0r** [comment]
Thanks, @dvrkps! Can you please add a `Signed-off-by` header to your commit to satisfy our [DCO](https://github.com/probot/dco#how-it-works)?

**Comment by adleong** [comment]
Thanks for the PR, @dvrkps.  Could you update the description to explain the motivation for this change?

**Comment by dvrkps** [comment]
@olix0r i don't know how to add this from website. 
i think you can added this because "Allow edits from maintainers." is checked.

**Comment by adleong** [comment]
@dvrkps [here are instructions](https://github.com/probot/dco#how-it-works) for adding the DCO signoff to your commit.

**Pull request closed without merging**
